### ISSUE TITLE
Hello! Not an Issue - Requesting Contact

### ISSUE THREAD

**Issue by mikeloveridge** [countmodula/VCVRackLunettaModula#4]
Hi,

My name is Mike Loveridge and I just saw your Lunetta modules in VCV Rack.  I must admit I'm mystified. I was a student of Stan back in the 70s and built my own digital synthesizer under his guidance.  I attached a snapshot of my cube sitting on my shelf.  I would love to find out more about you and how you came to know about his work.
He was an amazing man and miss him and his influence on me as a teenager.
I'd love to start a dialog with you and thank you for making this the most amazing day for me.  What a tribute to his work.  I can't wait to start playing with your modules and recreate in VCV Rack what I have sitting up on my shelf.  You can reach me by email or call me.
loveridgem@gmail.com
360-903-6703
Thanks!

![20200715_072559](https://user-images.githubusercontent.com/14959412/87557572-ea6cfc00-c66c-11ea-8eb8-c2ca243e85b7.jpg)

**Comment by AdamVerspaget** [comment]
Conversation continued on email.
